In [1]:
import numpy as np

In [16]:
matrix1 = np.array([[2,3],[6,7]])

In [18]:
matrix1


array([[2, 3],
       [6, 7]])

In [24]:
matrix1.shape

(2, 2)

In [27]:
matrix2 = np.array([[10,35,45],[50,60,70],[20,40,60]])

In [30]:
matrix2.shape

(3, 3)

In [37]:
random_matrix = np.random.rand(3,3)

In [41]:
random_matrix

array([[0.09472881, 0.67437509, 0.90060478],
       [0.05881803, 0.14457893, 0.78348898],
       [0.26979034, 0.5105515 , 0.2358326 ]])

In [80]:
random_matrix2 = np.random.randint(100, size=(4,5))

In [82]:
random_matrix2

array([[52, 59, 99, 74,  5],
       [78, 65, 27, 10, 80],
       [13, 69, 18, 87, 69],
       [90, 22, 85, 90, 40]])

In [90]:
matrix_3 = np.ones((2,3))
matrix_3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [93]:
matrix_4 = np.ones((2,3),dtype=int)
matrix_4

array([[1, 1, 1],
       [1, 1, 1]])

In [102]:
matrix_5 = np.zeros((10,10))
matrix_5

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [111]:
identity_matrix = np.eye(5,5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [117]:
transpose_of_matrix= np.transpose(random_matrix2)

In [123]:
print(random_matrix2)
print(transpose_of_matrix)

[[52 59 99 74  5]
 [78 65 27 10 80]
 [13 69 18 87 69]
 [90 22 85 90 40]]
[[52 78 13 90]
 [59 65 69 22]
 [99 27 18 85]
 [74 10 87 90]
 [ 5 80 69 40]]
